version: '3.8'

volumes:
  app_database: {}

networks:
  php_design_pattern_network:
    name: php_design_pattern_network
    driver: bridge

services:
  php_design_pattern:
    build: php
    hostname: phpdp
    volumes:
      - ../:/var/www/app:delegated
      - ./data/shell_history:/home/utente/shell_history
    environment:
      - HISTFILE=/home/utente/shell_history/.x_history
    networks:
      - php_design_pattern_network
    secrets:
      - source: id_rsa
        target: /home/utente/.ssh/id_rsa
      - source: id_rsa.pub
        target: /home/utente/.ssh/id_rsa.pub
      - source: known_hosts
        target: /home/utente/.ssh/known_hosts

  servicedb:
    image: mysql:5.7
    volumes:
      - app_database:/var/lib/mysql
    command: mysqld --sql_mode=""
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=idy
    networks:
      - php_design_pattern_network

  nodejs:
    build: nodejs
    working_dir: /var/www/app
    #command: "commitlint -e --from=HEAD"
    volumes:
      - ../:/var/www/app
    networks:
      - php_design_pattern_network