version: '3.7'

secrets:
  id_rsa:
    file: ~/.ssh/id_rsa
  id_rsa.pub:
    file: ~/.ssh/id_rsa.pub
  known_hosts:
    file: ~/.ssh/known_hosts

services:

  servicedb:
    ports:
      - "3307:3306"