#!/usr/bin/env php
<?php

require dirname(__DIR__).'/../../vendor/autoload.php';

use Symfony\Component\Console\Application;
use DesignPatterns\HexagonalArchitecture\Step04\Application\Service\Idea\CreateIdeaService;
use DesignPatterns\HexagonalArchitecture\Step04\Infrastracture\Delivery\Console\CreateIdeaCommand;
use DesignPatterns\HexagonalArchitecture\Step04\Infrastracture\Domain\Idea\MySql\MySqlIdeaRepository;

$application = new Application();

$application->add(
    new CreateIdeaCommand(
        new CreateIdeaService(new MySqlIdeaRepository())
    )
);

$application->run();
